# We are using the ionicons icon set https://ionic.io/ionicons
# For example, to add a linkedin icon:
# <ion-icon name="logo-linkedin"></ion-icon>
# - icon: "logo-linkedin"

HEADER:
  label: "Show Contacts"

USER:
  role: "R&D Hardware Engineer"
  name: "Bayu Arivia Putra"
  username: "fnnxtion" # <-- This needs to be the same as your GitHub username
  avatar: "config/assets/avatars/my-avatar.png"

INFO:
  - label: "Email"
    value: "ariviabayu@gmail.com"
    icon: "mail-outline"
  - label: "Phone"
    value: "+62895-4127-75900"
    icon: "phone-portrait-outline"
  - label: "Birthday"
    value: "December 1, 2001"
    icon: "calendar-outline"
  - label: "Location"
    value: "Batam, Riau Island, Indonesia"
    icon: "location-outline"

SOCIAL:
  - icon: "logo-facebook"
    url: "https://facebook.com/"
  - icon: "logo-twitter"
    url: "https://twitter.com/"
  - icon: "logo-instagram"
    url: "https://instagram.com/"
  - icon: "logo-linkedin"
    url: "https://www.linkedin.com/bayuarivia"
  - icon: "logo-github"
    url: "https://github.com/ivansaul"
  - icon: "logo-dribbble"
    url: "https://dribbble.com/"
